// Common 5-letter words for Wordle
export const WORDS = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
  "agent", "agree", "ahead", "alarm", "album", "alert", "alien", "align", "alike", "alive",
  "allow", "alone", "along", "alter", "among", "anger", "angle", "angry", "apart", "apple",
  "apply", "arena", "argue", "arise", "armed", "armor", "array", "arrow", "asset", "avoid",
  "award", "aware", "awful", "badge", "badly", "baker", "basic", "basis", "beach", "began",
  "begin", "begun", "being", "belly", "below", "bench", "berry", "birth", "black", "blade",
  "blame", "blank", "blast", "blaze", "blend", "bless", "blind", "block", "blood", "bloom",
  "blown", "blues", "blunt", "board", "boast", "bonus", "boost", "booth", "bound", "brain",
  "brand", "brass", "brave", "bread", "break", "breed", "brick", "bride", "brief", "bring",
  "broad", "broke", "brown", "brush", "build", "built", "bunch", "burst", "buyer", "cable",
  "camel", "candy", "cargo", "carry", "catch", "cause", "chain", "chair", "charm", "chart",
  "chase", "cheap", "check", "cheek", "chest", "chief", "child", "china", "chose", "chunk",
  "civic", "civil", "claim", "class", "clean", "clear", "clerk", "click", "cliff", "climb",
  "clock", "close", "cloth", "cloud", "coach", "coast", "colon", "color", "couch", "could",
  "count", "court", "cover", "crack", "craft", "crane", "crash", "crawl", "crazy", "cream",
  "crime", "crisp", "cross", "crowd", "crown", "cruel", "crush", "curve", "cycle", "daily",
  "dance", "dated", "dealt", "death", "debut", "decay", "delay", "delta", "dense", "depth",
  "diary", "dirty", "doubt", "dough", "dozen", "draft", "drain", "drama", "drank", "drawn",
  "dream", "dress", "dried", "drift", "drill", "drink", "drive", "drown", "drunk", "dying",
  "eager", "early", "earth", "eater", "eight", "elder", "elite", "empty", "enemy", "enjoy",
  "enter", "entry", "equal", "error", "essay", "event", "every", "exact", "exist", "extra",
  "faint", "faith", "false", "fancy", "fatal", "fault", "favor", "feast", "fence", "ferry",
  "fever", "fiber", "field", "fifth", "fifty", "fight", "final", "first", "fixed", "flame",
  "flash", "flask", "flesh", "float", "flood", "floor", "flour", "fluid", "flush", "focus",
  "force", "forge", "forth", "forty", "forum", "found", "frame", "frank", "fraud", "fresh",
  "front", "frost", "fruit", "fully", "funny", "ghost", "giant", "given", "glass", "globe",
  "glory", "glove", "grace", "grade", "grain", "grand", "grant", "grape", "grasp", "grass",
  "grave", "great", "green", "greet", "grief", "grill", "grind", "gross", "group", "grove",
  "grown", "guard", "guess", "guest", "guide", "guild", "habit", "handy", "happy", "harsh",
  "haste", "haunt", "haven", "heart", "heavy", "hence", "honey", "honor", "horse", "hotel",
  "house", "human", "humor", "hurry", "ideal", "image", "imply", "index", "inner", "input",
  "irony", "issue", "ivory", "jeans", "jewel", "joint", "joker", "jolly", "judge", "juice",
  "jumbo", "karma", "kayak", "knife", "knock", "known", "label", "labor", "lance", "large",
  "laser", "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon",
  "level", "lever", "light", "limit", "linen", "liner", "liver", "lobby", "local", "logic",
  "loose", "lorry", "loser", "lover", "lower", "loyal", "lucky", "lunch", "lying", "magic",
  "major", "maker", "march", "marry", "marsh", "match", "maybe", "mayor", "medal", "media",
  "melon", "mercy", "merge", "merit", "merry", "metal", "meter", "might", "minor", "minus",
  "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth", "movie",
  "music", "naked", "nasty", "naval", "nerve", "never", "newly", "night", "noble", "noise",
  "north", "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "olive", "onion",
  "opera", "orbit", "order", "organ", "other", "ought", "outer", "owner", "oxide", "ozone",
  "paint", "panel", "panic", "paper", "party", "pasta", "patch", "pause", "peace", "peach",
  "pearl", "penny", "perch", "phase", "phone", "photo", "piano", "piece", "pilot", "pinch",
  "pitch", "pizza", "place", "plain", "plane", "plant", "plate", "plaza", "plead", "pluck",
  "plumb", "point", "polar", "polls", "pound", "power", "press", "price", "pride", "prime",
  "print", "prior", "prize", "probe", "proof", "proud", "prove", "proxy", "pupil", "purse",
  "queen", "query", "quest", "queue", "quick", "quiet", "quilt", "quota", "quote", "radar",
  "radio", "raise", "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready",
  "realm", "rebel", "refer", "reign", "relax", "reply", "rider", "ridge", "rifle", "right",
  "rigid", "rigor", "rinse", "risky", "rival", "river", "robin", "robot", "rocky", "roman",
  "rough", "round", "route", "royal", "rural", "sadly", "safer", "saint", "salad", "salon",
  "sandy", "satin", "sauce", "scale", "scare", "scene", "scent", "scoop", "scope", "score",
  "scout", "scrap", "serve", "setup", "seven", "shade", "shake", "shall", "shame", "shape",
  "share", "shark", "sharp", "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine",
  "shirt", "shock", "shore", "short", "shout", "sight", "silly", "since", "sixth", "sixty",
  "sized", "skill", "skirt", "skull", "slave", "sleep", "slice", "slide", "slope", "small",
  "smart", "smell", "smile", "smith", "smoke", "snack", "snake", "solar", "solid", "solve",
  "sorry", "sound", "south", "space", "spare", "spark", "speak", "speed", "spell", "spend",
  "spent", "spice", "spill", "spine", "spite", "split", "spoke", "spoon", "sport", "spray",
  "squad", "stack", "staff", "stage", "stain", "stake", "stamp", "stand", "stark", "start",
  "state", "steak", "steam", "steel", "steep", "steer", "stern", "stick", "stiff", "still",
  "stock", "stone", "stood", "store", "storm", "story", "stove", "strap", "straw", "strip",
  "stuck", "study", "stuff", "style", "sugar", "suite", "sunny", "super", "surge", "sweet",
  "swift", "swing", "swiss", "sword", "table", "taken", "taste", "teach", "teens", "tempo",
  "tense", "tenth", "terms", "thank", "theft", "their", "theme", "there", "these", "thick",
  "thief", "thing", "think", "third", "those", "three", "threw", "throw", "thumb", "tight",
  "timer", "tired", "title", "today", "token", "tooth", "topic", "torch", "total", "touch",
  "tough", "tower", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "trend", "trial", "tribe", "trick", "tried", "troop", "truck", "truly", "trunk",
  "trust", "truth", "tumor", "tutor", "twice", "twist", "uncle", "under", "unify", "union",
  "unite", "unity", "until", "upper", "upset", "urban", "usage", "usual", "valid", "value",
  "valve", "vapor", "vault", "venue", "verse", "video", "views", "vigor", "viral", "virus",
  "visit", "vital", "vivid", "vocal", "voice", "voter", "wagon", "waist", "waste", "watch",
  "water", "weary", "weigh", "weird", "whale", "wheat", "wheel", "where", "which", "while",
  "white", "whole", "whose", "widow", "width", "witch", "woman", "world", "worry", "worse",
  "worst", "worth", "would", "wound", "woven", "wrist", "write", "wrong", "wrote", "yacht",
  "yield", "young", "yours", "youth", "zebra", "zesty"
];

// Valid guesses (includes WORDS plus additional valid words)
export const VALID_GUESSES = new Set([
  ...WORDS,
  "spain", "brain", "train", "drain", "grain", "plain", "slain", "stain", "chain", "claim",
  "aahed", "aalii", "aargh", "abaca", "abaci", "aback", "abaft", "abamp", "abase", "abash",
  "abate", "abaya", "abbey", "abbot", "abeam", "abele", "abets", "abhor", "abide", "abled",
  "abler", "abmho", "abode", "abohm", "aboil", "aboma", "aboon", "abort", "abris", "abuzz",
  "abyes", "abysm", "abyss", "acari", "acerb", "aceta", "ached", "aches", "achoo", "acids",
  "acidy", "acing", "acini", "ackee", "acmes", "acmic", "acned", "acnes", "acock", "acold",
  "acorn", "acres", "acrid", "acted", "actin", "acute", "acyls", "adage", "adapt", "addax",
  "added", "adder", "addle", "adeem", "adept", "adieu", "adios", "admit", "admix", "adobe",
  "adobo", "adopt", "adore", "adorn", "adown", "adult", "adunc", "adust", "adyta", "aeons",
  "aerie", "afars", "affix", "afire", "afoot", "afore", "afoul", "afrit", "after", "again",
  "agama", "agape", "agars", "agate", "agave", "agaze", "agent", "agers", "agger", "aggie",
  "aggro", "aghas", "agile", "aging", "agios", "agism", "agist", "aglee", "aglet", "agley",
  "aglow", "agmas", "agone", "agons", "agony", "agora", "agree", "agria", "ahead", "ahing",
  "aided", "aider", "aides", "ailed", "aimed", "aimer", "aioli", "aired", "airer", "airns",
  "airth", "airts", "aisle", "aitch", "aiver", "ajiva", "ajwan", "akees", "akela", "akene",
  "alack", "alamo", "aland", "alane", "alang", "alans", "alarm", "alary", "alate", "albas",
  "album", "alcid", "alder", "aldol", "alecs", "alefs", "aleph", "alert", "alfas", "algae",
  "algal", "algas", "algid", "algin", "algor", "algum", "alias", "alibi", "alien", "alifs",
  "align", "alike", "aline", "alist", "alive", "aliya", "allay", "alley", "allod", "allot",
  "allow", "alloy", "allyl", "almah", "almas", "almeh", "almes", "almud", "almug", "aloes",
  "aloft", "aloha", "alone", "along", "aloof", "aloud", "alpha", "altar", "alter", "altho",
  "altos", "alula", "alums", "alway", "amahs", "amain", "amass", "amaze", "amber", "ambit",
  "amble", "ambos", "ambry", "ameba", "ameer", "amend", "amens", "ament", "amias", "amice",
  "amici", "amide", "amids", "amies", "amine", "amino", "amins", "amirs", "amiss", "amity",
  "ammos", "amnia", "amnic", "amnio", "amoks", "amole", "among", "amort", "amour", "amped",
  "ample", "amply", "ampul", "amuck", "amuse", "amyls", "ancho", "angel", "anger", "angle",
  "angry", "angst", "anile", "anima", "anime", "animi", "anion", "anise", "ankhs", "ankle",
  "anlas", "annas", "annex", "annoy", "annul", "anoas", "anode", "anole", "anted", "antes",
  "antic", "antis", "antra", "antre", "antsy", "anvil", "apart", "aping", "apish", "apnea",
  "apods", "aport", "appal", "appel", "apple", "apply", "apres", "apron", "apses", "apsis",
  "aptly", "aquae", "aquas", "araks", "arbor", "arced", "arcus", "ardeb", "ardor", "areal",
  "areas", "areca", "arena", "arene", "arepa", "arete", "argal", "argil", "argle", "argol",
  "argon", "argot", "argue", "argus", "arhat", "arias", "ariel", "arils", "arise", "arles",
  "armed", "armer", "armet", "armor", "aroid", "aroma", "arose", "array", "arrow", "arses",
  "arsis", "arson", "artal", "artel", "artsy", "aruhe", "arums", "arval", "aryan", "ashed",
  "ashen", "ashes", "aside", "asked", "asker", "askew", "askoi", "askos", "aspen", "asper",
  "aspic", "aspis", "assai", "assay", "asses", "asset", "aster", "astir", "atlas", "atmas",
  "atoll", "atoms", "atone", "atony", "atopy", "atria", "atrip", "attic", "audad", "audio",
  "audit", "auger", "aught", "augur", "aunts", "aunty", "aurae", "aural", "aurar", "auras",
  "aurei", "aures", "auric", "auris", "aurum", "autos", "auxin", "avail", "avant", "avast",
  "avens", "avers", "avert", "avgas", "avian", "avion", "aviso", "avoid", "avows", "await",
  "awake", "award", "aware", "awash", "awful", "awing", "awned", "awning", "awoke", "awols",
  "axels", "axial", "axile", "axils", "axing", "axiom", "axion", "axite", "axled", "axles",
  "axman", "axmen", "axone", "axons", "ayahs", "azans", "azide", "azido", "azine", "azlon",
  "azoic", "azole", "azons", "azote", "azoth", "azuki", "azure"
]);

export function getRandomWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)].toUpperCase();
}

export function isValidWord(word: string): boolean {
  return VALID_GUESSES.has(word.toLowerCase());
}
